import type { CatalogItem, PresetQuery } from "./types";

/** Frozen workspace clock so fixture ranking stays deterministic. */
export const WORKSPACE_NOW = "2026-09-28T15:04:00.000Z";

export const PRESET_QUERIES: PresetQuery[] = [
  { label: "the pdf I just downloaded", query: "the pdf I just downloaded" },
  { label: "waiting on legal to sign", query: "waiting on legal to sign" },
  { label: "MSA countersign", query: "MSA countersign" },
  { label: "expired signature requests", query: "expired signature requests" },
];

export const CATALOG: CatalogItem[] = [
  {
    id: "pdf-q3-board-deck",
    kind: "pdf",
    title: "Q3 Board Deck.pdf",
    subtitle: "Downloaded 8 minutes ago · 42 pages",
    aliases: ["board deck", "q3 slides", "board presentation"],
    tags: ["finance", "board"],
    modified_at: "2026-09-28T14:40:00.000Z",
    downloaded_at: "2026-09-28T14:56:00.000Z",
    owner: "You",
  },
  {
    id: "pdf-expense-sep",
    kind: "pdf",
    title: "September Expense Report.pdf",
    subtitle: "Downloaded yesterday · Finance",
    aliases: ["expenses", "reimbursement"],
    tags: ["finance"],
    modified_at: "2026-09-27T17:20:00.000Z",
    downloaded_at: "2026-09-27T18:10:00.000Z",
    owner: "You",
  },
  {
    id: "pdf-harbor-sow",
    kind: "pdf",
    title: "Harbor Notes SOW.pdf",
    subtitle: "Downloaded 2 days ago · Vendor",
    aliases: ["statement of work", "harbor"],
    tags: ["vendor", "legal"],
    modified_at: "2026-09-26T10:15:00.000Z",
    downloaded_at: "2026-09-26T11:00:00.000Z",
    owner: "Priya Chen",
  },
  {
    id: "pdf-insurance",
    kind: "pdf",
    title: "Vendor Insurance Certificate.pdf",
    subtitle: "Downloaded last week · Compliance",
    aliases: ["coi", "certificate of insurance"],
    tags: ["compliance"],
    modified_at: "2026-09-21T08:40:00.000Z",
    downloaded_at: "2026-09-21T09:00:00.000Z",
    owner: "Ops",
  },
  {
    id: "pdf-acme-msa-executed",
    kind: "pdf",
    title: "Acme MSA (fully executed).pdf",
    subtitle: "Signed copy · downloaded 3 weeks ago",
    aliases: ["master service agreement", "acme contract"],
    tags: ["legal", "msa"],
    modified_at: "2026-09-08T15:50:00.000Z",
    downloaded_at: "2026-09-08T16:00:00.000Z",
    owner: "Legal",
  },
  {
    id: "doc-q4-hiring",
    kind: "doc",
    title: "Q4 Hiring Plan",
    subtitle: "Lumin Doc · edited this morning",
    aliases: ["headcount", "hiring"],
    tags: ["people"],
    modified_at: "2026-09-28T13:10:00.000Z",
    owner: "You",
  },
  {
    id: "doc-security-q",
    kind: "doc",
    title: "Security Questionnaire — Acme",
    subtitle: "Lumin Doc · shared with Security",
    aliases: ["siglite", "security review"],
    tags: ["security", "acme"],
    modified_at: "2026-09-25T19:00:00.000Z",
    owner: "Security",
  },
  {
    id: "doc-brand",
    kind: "doc",
    title: "Brand Guidelines 2026",
    subtitle: "Lumin Doc · Marketing",
    aliases: ["brand book", "style guide"],
    tags: ["marketing"],
    modified_at: "2026-09-12T11:00:00.000Z",
    owner: "Marketing",
  },
  {
    id: "sig-msa-countersign",
    kind: "signature",
    title: "Acme MSA — countersign",
    subtitle: "Waiting on Acme Legal · you already signed",
    aliases: ["msa countersign", "master service agreement", "acme msa"],
    tags: ["legal", "msa", "countersign"],
    modified_at: "2026-09-27T21:05:00.000Z",
    status: "waiting",
    parties: ["You (signed)", "Acme Legal"],
    owner: "Legal",
  },
  {
    id: "sig-nda-contoso",
    kind: "signature",
    title: "Contoso mutual NDA",
    subtitle: "Completed · both parties signed",
    aliases: ["nda", "contoso"],
    tags: ["legal", "nda"],
    modified_at: "2026-09-20T16:00:00.000Z",
    status: "completed",
    parties: ["You (signed)", "Contoso Legal (signed)"],
    owner: "Legal",
  },
  {
    id: "sig-offer-jordan",
    kind: "signature",
    title: "Offer letter — Jordan Lee",
    subtitle: "Waiting on candidate",
    aliases: ["offer", "jordan"],
    tags: ["people"],
    modified_at: "2026-09-28T09:30:00.000Z",
    status: "waiting",
    parties: ["You (signed)", "Jordan Lee"],
    owner: "People",
  },
  {
    id: "sig-dpa-expired",
    kind: "signature",
    title: "Vendor DPA — Northwind",
    subtitle: "Expired 4 days ago · no countersignature",
    aliases: ["dpa", "data processing", "northwind"],
    tags: ["legal", "privacy"],
    modified_at: "2026-09-18T12:00:00.000Z",
    status: "expired",
    parties: ["You (signed)", "Northwind Legal"],
    owner: "Legal",
  },
  {
    id: "sig-partner-expired",
    kind: "signature",
    title: "Partner addendum — Brightline",
    subtitle: "Expired last week · waiting never completed",
    aliases: ["partner", "addendum", "brightline"],
    tags: ["legal", "partner"],
    modified_at: "2026-09-14T08:00:00.000Z",
    status: "expired",
    parties: ["You", "Brightline Counsel"],
    owner: "Legal",
  },
  {
    id: "sig-board-consent",
    kind: "signature",
    title: "Written board consent — option grant",
    subtitle: "Waiting on two directors",
    aliases: ["board consent", "option grant"],
    tags: ["board"],
    modified_at: "2026-09-26T15:00:00.000Z",
    status: "waiting",
    parties: ["Avery Kim", "Sam Ortiz"],
    owner: "Legal",
  },
  {
    id: "folder-closed",
    kind: "folder",
    title: "Closed deals",
    subtitle: "12 documents",
    aliases: ["won", "closed-won"],
    tags: ["sales"],
    modified_at: "2026-09-22T10:00:00.000Z",
    owner: "Sales",
  },
  {
    id: "folder-templates",
    kind: "folder",
    title: "Template library",
    subtitle: "MSA, NDA, offer, DPA",
    aliases: ["templates folder"],
    tags: ["templates"],
    modified_at: "2026-09-10T09:00:00.000Z",
    owner: "Legal",
  },
  {
    id: "tpl-msa",
    kind: "template",
    title: "MSA template",
    subtitle: "Lumin template · Legal",
    aliases: ["master service agreement template"],
    tags: ["legal", "msa"],
    modified_at: "2026-08-30T12:00:00.000Z",
    owner: "Legal",
  },
  {
    id: "tpl-nda",
    kind: "template",
    title: "Mutual NDA template",
    subtitle: "Lumin template · Legal",
    aliases: ["nda template"],
    tags: ["legal", "nda"],
    modified_at: "2026-08-28T12:00:00.000Z",
    owner: "Legal",
  },
];

export function slimCatalog(): Array<Record<string, unknown>> {
  return CATALOG.map((item) => ({
    id: item.id,
    kind: item.kind,
    title: item.title,
    subtitle: item.subtitle,
    status: item.status ?? null,
    parties: item.parties ?? [],
    downloaded_at: item.downloaded_at ?? null,
    modified_at: item.modified_at,
    tags: item.tags,
  }));
}
