import type { TestPlan } from "./types";

export const PLANS: TestPlan[] = [
  {
    id: "happy-path-send",
    title: "Happy-path send",
    summary: "Fill title and signer, send the request, assert Sent.",
    steps: [
      {
        id: "hp-title",
        title: "Set document title",
        intent: "Name this signature request so it can be sent.",
        primitive: "choice",
        expectedActionId: "type-title",
        actionSpace: [
          {
            id: "type-title",
            kind: "type",
            target: "title",
            value: "Q3 Vendor MSA",
            label: "Type title “Q3 Vendor MSA”",
          },
          {
            id: "type-wrong-title",
            kind: "type",
            target: "title",
            value: "Untitled draft",
            label: "Type title “Untitled draft”",
          },
          {
            id: "click-send-early",
            kind: "click",
            target: "send",
            label: "Click Send now",
          },
          {
            id: "click-decline-early",
            kind: "click",
            target: "decline",
            label: "Click Decline",
          },
        ],
      },
      {
        id: "hp-name",
        title: "Add signer name",
        intent: "Fill the required signer name field.",
        primitive: "choice",
        expectedActionId: "type-name",
        actionSpace: [
          {
            id: "type-name",
            kind: "type",
            target: "signer-name",
            value: "Ada Lovelace",
            label: "Type signer name “Ada Lovelace”",
          },
          {
            id: "type-blank-name",
            kind: "type",
            target: "signer-name",
            value: "",
            label: "Clear the signer name",
          },
          {
            id: "click-send-name",
            kind: "click",
            target: "send",
            label: "Click Send without an email",
          },
        ],
      },
      {
        id: "hp-email",
        title: "Add signer email",
        intent: "Fill a valid signer email so Send is allowed.",
        primitive: "choice",
        expectedActionId: "type-email",
        actionSpace: [
          {
            id: "type-email",
            kind: "type",
            target: "signer-email",
            value: "ada@lumin.example",
            label: "Type signer email ada@lumin.example",
          },
          {
            id: "type-bad-email",
            kind: "type",
            target: "signer-email",
            value: "not-an-email",
            label: "Type an invalid email",
          },
          {
            id: "type-message",
            kind: "type",
            target: "message",
            value: "Please review by Friday.",
            label: "Type a request message only",
          },
        ],
      },
      {
        id: "hp-send",
        title: "Send the request",
        intent: "Send the completed signature request.",
        primitive: "choice",
        expectedActionId: "click-send",
        actionSpace: [
          {
            id: "click-send",
            kind: "click",
            target: "send",
            label: "Click Send request",
          },
          {
            id: "click-decline",
            kind: "click",
            target: "decline",
            label: "Click Decline",
          },
          {
            id: "retype-title",
            kind: "type",
            target: "title",
            value: "Q3 Vendor MSA (revised)",
            label: "Rewrite the title instead of sending",
          },
        ],
      },
      {
        id: "hp-assert",
        title: "Assert status is Sent",
        intent: "The fixture status badge should read sent after a valid send.",
        primitive: "score",
        expectedActionId: "assert-sent",
        actionSpace: [
          {
            id: "assert-sent",
            kind: "assert-status",
            expected: "sent",
            target: "status",
            label: "Assert status is sent",
          },
          {
            id: "assert-draft",
            kind: "assert-status",
            expected: "draft",
            target: "status",
            label: "Assert status is draft",
          },
          {
            id: "assert-declined",
            kind: "assert-status",
            expected: "declined",
            target: "status",
            label: "Assert status is declined",
          },
        ],
      },
    ],
  },
  {
    id: "missing-signer-fail",
    title: "Missing-signer fail",
    summary: "Send with a title only; expect a signer error and Blocked.",
    steps: [
      {
        id: "ms-title",
        title: "Set title only",
        intent: "Give the request a title but leave the signer empty.",
        primitive: "choice",
        expectedActionId: "type-title",
        actionSpace: [
          {
            id: "type-title",
            kind: "type",
            target: "title",
            value: "NDA — missing signer",
            label: "Type title “NDA — missing signer”",
          },
          {
            id: "type-name",
            kind: "type",
            target: "signer-name",
            value: "Grace Hopper",
            label: "Type a signer name (would hide the fail path)",
          },
          {
            id: "click-decline",
            kind: "click",
            target: "decline",
            label: "Click Decline",
          },
        ],
      },
      {
        id: "ms-send",
        title: "Send without a signer",
        intent: "Attempt Send while signer fields are empty to surface the error.",
        primitive: "choice",
        expectedActionId: "click-send",
        actionSpace: [
          {
            id: "click-send",
            kind: "click",
            target: "send",
            label: "Click Send request",
          },
          {
            id: "type-email",
            kind: "type",
            target: "signer-email",
            value: "grace@lumin.example",
            label: "Add a signer email instead",
          },
          {
            id: "click-decline",
            kind: "click",
            target: "decline",
            label: "Click Decline",
          },
        ],
      },
      {
        id: "ms-error",
        title: "Expect signer error",
        intent: "An error banner should mention the missing signer.",
        primitive: "score",
        expectedActionId: "expect-signer-error",
        actionSpace: [
          {
            id: "expect-signer-error",
            kind: "expect-error",
            match: "signer",
            target: "error-banner",
            label: "Expect an error mentioning signer",
          },
          {
            id: "expect-network-error",
            kind: "expect-error",
            match: "network",
            target: "error-banner",
            label: "Expect a network error",
          },
          {
            id: "assert-sent",
            kind: "assert-status",
            expected: "sent",
            target: "status",
            label: "Assert status is sent",
          },
        ],
      },
      {
        id: "ms-status",
        title: "Assert status is Blocked",
        intent: "The fixture should be blocked, not sent.",
        primitive: "score",
        expectedActionId: "assert-blocked",
        actionSpace: [
          {
            id: "assert-blocked",
            kind: "assert-status",
            expected: "blocked",
            target: "status",
            label: "Assert status is blocked",
          },
          {
            id: "assert-sent",
            kind: "assert-status",
            expected: "sent",
            target: "status",
            label: "Assert status is sent",
          },
          {
            id: "assert-ready",
            kind: "assert-status",
            expected: "ready",
            target: "status",
            label: "Assert status is ready",
          },
        ],
      },
    ],
  },
  {
    id: "decline-recovery",
    title: "Decline recovery",
    summary: "Complete the form, decline, then send to recover.",
    steps: [
      {
        id: "dr-title",
        title: "Set document title",
        intent: "Name the request before declining it.",
        primitive: "choice",
        expectedActionId: "type-title",
        actionSpace: [
          {
            id: "type-title",
            kind: "type",
            target: "title",
            value: "Offer letter — recovery",
            label: "Type title “Offer letter — recovery”",
          },
          {
            id: "click-decline-early",
            kind: "click",
            target: "decline",
            label: "Decline before filling fields",
          },
          {
            id: "click-send-early",
            kind: "click",
            target: "send",
            label: "Click Send now",
          },
        ],
      },
      {
        id: "dr-name",
        title: "Add signer name",
        intent: "Fill the signer name so a later send can succeed.",
        primitive: "choice",
        expectedActionId: "type-name",
        actionSpace: [
          {
            id: "type-name",
            kind: "type",
            target: "signer-name",
            value: "Katherine Johnson",
            label: "Type signer name “Katherine Johnson”",
          },
          {
            id: "click-decline",
            kind: "click",
            target: "decline",
            label: "Click Decline",
          },
          {
            id: "type-message",
            kind: "type",
            target: "message",
            value: "Need this countersigned.",
            label: "Type a message only",
          },
        ],
      },
      {
        id: "dr-email",
        title: "Add signer email",
        intent: "Fill a valid signer email.",
        primitive: "choice",
        expectedActionId: "type-email",
        actionSpace: [
          {
            id: "type-email",
            kind: "type",
            target: "signer-email",
            value: "kj@lumin.example",
            label: "Type signer email kj@lumin.example",
          },
          {
            id: "type-bad-email",
            kind: "type",
            target: "signer-email",
            value: "kj@",
            label: "Type an incomplete email",
          },
          {
            id: "click-send",
            kind: "click",
            target: "send",
            label: "Click Send before declining",
          },
        ],
      },
      {
        id: "dr-decline",
        title: "Decline the request",
        intent: "Decline the completed request to enter the recovery path.",
        primitive: "choice",
        expectedActionId: "click-decline",
        actionSpace: [
          {
            id: "click-decline",
            kind: "click",
            target: "decline",
            label: "Click Decline",
          },
          {
            id: "click-send",
            kind: "click",
            target: "send",
            label: "Click Send request",
          },
          {
            id: "clear-name",
            kind: "type",
            target: "signer-name",
            value: "",
            label: "Clear the signer name",
          },
        ],
      },
      {
        id: "dr-assert-declined",
        title: "Assert status is Declined",
        intent: "The fixture should show declined after Decline.",
        primitive: "score",
        expectedActionId: "assert-declined",
        actionSpace: [
          {
            id: "assert-declined",
            kind: "assert-status",
            expected: "declined",
            target: "status",
            label: "Assert status is declined",
          },
          {
            id: "assert-sent",
            kind: "assert-status",
            expected: "sent",
            target: "status",
            label: "Assert status is sent",
          },
          {
            id: "expect-error",
            kind: "expect-error",
            match: "signer",
            target: "error-banner",
            label: "Expect a signer error",
          },
        ],
      },
      {
        id: "dr-resend",
        title: "Send after decline",
        intent: "Recover by sending the still-complete request.",
        primitive: "choice",
        expectedActionId: "click-send",
        actionSpace: [
          {
            id: "click-send",
            kind: "click",
            target: "send",
            label: "Click Send request",
          },
          {
            id: "click-decline-again",
            kind: "click",
            target: "decline",
            label: "Click Decline again",
          },
          {
            id: "wipe-email",
            kind: "type",
            target: "signer-email",
            value: "",
            label: "Clear the signer email",
          },
        ],
      },
      {
        id: "dr-assert-sent",
        title: "Assert status is Sent",
        intent: "After recovery send, status should be sent.",
        primitive: "score",
        expectedActionId: "assert-sent",
        actionSpace: [
          {
            id: "assert-sent",
            kind: "assert-status",
            expected: "sent",
            target: "status",
            label: "Assert status is sent",
          },
          {
            id: "assert-declined",
            kind: "assert-status",
            expected: "declined",
            target: "status",
            label: "Assert status is declined",
          },
          {
            id: "assert-blocked",
            kind: "assert-status",
            expected: "blocked",
            target: "status",
            label: "Assert status is blocked",
          },
        ],
      },
    ],
  },
];

export function planById(id: string): TestPlan {
  const plan = PLANS.find((item) => item.id === id);
  if (!plan) {
    throw new Error(`Unknown plan: ${id}`);
  }
  return plan;
}
